#
# install.R, 28 May 19
#
# This R program installs the packages used in the
# code for the examples in:
# Evidence-based Software Engineering: based on the publicly available data
# Derek M. Jones
#

install.packages("alluvial")
install.packages("ape")
install.packages("arules")
install.packages("ascii")
install.packages("beanplot")
install.packages("betareg")
install.packages("biglm")
install.packages("bitops")
install.packages("bizdays")
install.packages("boot")
install.packages("bootstrap")
install.packages("BradleyTerry2")
install.packages("car")
install.packages(car)
install.packages("changepoint")
install.packages("chngpt")
install.packages(choroplethr)
install.packages(choroplethrMaps)
install.packages("circular")
install.packages("cmprsk")
install.packages("coin")
install.packages("COMPoissonReg")
install.packages("compositions")
install.packages("corrgram")
install.packages("deming")
install.packages("dendextend")
install.packages(deSolve)
install.packages("dgof")
install.packages("diagram")
install.packages("DoE.base")
install.packages("dtw")
install.packages(ellipse)
install.packages("fitdistrplus")
install.packages(fitdistrplus)
install.packages("forecast")
install.packages("foreign")
install.packages("FrF2")
install.packages("gamlss")
install.packages(gamlss)
install.packages("gamlss.tr")
install.packages(gamlss.tr)
install.packages("ggplot2")
install.packages(ggplot2)
install.packages("gnm")
install.packages("gnm") 
install.packages("gplots")
install.packages("gridExtra")
install.packages("grid") # Yes, seriation uses grid graphics
install.packages("igraph")
install.packages(igraph)
install.packages("iNEXT") # defines its own ChaoSpecies function
install.packages("irr")
install.packages(jsonlite)
install.packages("ks")
install.packages("kSamples")
install.packages("lattice")
install.packages(lattice)
install.packages("latticeExtra")
install.packages(latticeExtra)
install.packages("libstableR")
install.packages("lme4")
install.packages(lme4)
install.packages("lmodel2")
install.packages("ltm")
install.packages("lubridate")
install.packages(lubridate)
install.packages(maps)
install.packages(maptools)
install.packages("MASS")
install.packages(MASS)
install.packages("Matrix") # sparse.model.matrix is referenced by a function in quantreg
install.packages("mgcv")
install.packages("mixtools")
install.packages("msm")
install.packages(mvtnorm)
install.packages("nlme")
install.packages(numDeriv)
install.packages("ordinal")
install.packages(pdq)
install.packages("penalized")
install.packages("pglm")
install.packages("phangorn")
install.packages("plan")
install.packages("plyr")
install.packages(plyr)
install.packages("png")
install.packages("poweRlaw")
install.packages("prefmod")
install.packages("pwr")
install.packages("quantreg")
install.packages("RANN")
install.packages("Rcapture")
install.packages("RcppCNPy")
install.packages("rebmix")
install.packages("relaimpo")
install.packages("reshape2")
install.packages(reshape2)
install.packages(rgdal)
install.packages("riverplot")
install.packages("RJSONIO")
install.packages(Rmisc)
install.packages("rms")
install.packages(rms)
install.packages("robustbase")
install.packages("ROCR")
install.packages("rpart")
install.packages("rpart.plot")
install.packages("RSQLite")
install.packages(scales)
install.packages("scatterplot3d")
install.packages("seriation")
install.packages("Sim.DiffProc")
install.packages("simex")
install.packages("simmer")
install.packages("sm")
install.packages("sna")
install.packages("snatm")
install.packages(sp)
install.packages("SpadeR")
install.packages("stringr")
install.packages("survival")
install.packages(survival)
install.packages("tm")
install.packages(tm)
install.packages("tm.plugin.mail")
install.packages("treemap")
install.packages("TSclust")
install.packages("VennDiagram")
install.packages("VGAM")
install.packages("visreg")
install.packages("WRS")
install.packages("XML")
install.packages("zoo")
# library("betareg")
# library("boot")
# library("changepoint")
# library("coin")
# library("COMPoissonReg")
# library("dgof")
# library("DoE.base")
# library("dply")
# library("extraDistr")
# library("feature")
# library("fitdistrplus")
# library(fitdistrplus)
# library("foreign")
# library("gamlss")
	library(ggplot2)
# library("gnm")
# library("gplots")
# library("gridExtra")
# library("hexbin")
# library("Hmisc")
# library("kSamples")
# library("lattice")
# library(limSolve)
# library("lme4")
#library("lmerTest")
# library("lubridate")
# library("MASS")
# library("Matrix") # sparse.model.matrix is referenced by a function in quantreg
# library("nlme")
# library("plyr")
	library(plyr)
# library("poweRlaw")
# library("quantreg")
	library(RColorBrewer)
# library("rebmix")
# library("reshape2")
	library(reshape2)
# library(rgdal)
# library("robustbase")
# library(robustbase)
# library(RSVGTipsDevice)
# library("sandwich")
# library("semver")
# library("sjPlot")
# library("TSclust")
# library("vioplot")
# library("WRS")
