#
# install.R, 16 Jan 16
#
# This R program installs all of the packages used in the
# code for the examples in:
# Empirical Software Engineering using R
# Derek M. Jones
#

install.packages("alluvial")
install.packages("ascii")
install.packages("beanplot")
install.packages("betareg")
install.packages("biglm")
install.packages("bitops")
install.packages("boot")
install.packages("bootstrap")
# install.packages("car")
install.packages("car")
install.packages("changepoint")
install.packages("circular")
install.packages(circular)
install.packages("cmprsk")
# install.packages("coin")
install.packages("coin")
install.packages("compositions")
install.packages("corrgram")
install.packages("deming")
# install.packages("dgof")
install.packages("dgof")
install.packages("diagram")
# install.packages("DoE.base")
install.packages("DoE.base")
install.packages("dtw")
install.packages(ellipse)
# install.packages("feature")
# install.packages("fitdistrplus")
install.packages("fitdistrplus")
install.packages(fitdistrplus)
# install.packages("forecast")
install.packages("forecast")
install.packages("foreign")
install.packages("FrF2")
install.packages("gamlss")
install.packages(gamlss)
install.packages(gamlss.tr)
install.packages(ggplot2)
# install.packages("gnm")
install.packages("gnm")
# install.packages("gplots")
install.packages("gplots")
# install.packages("gridExtra")
install.packages("gridExtra")
install.packages("grid") # Yes, seriation uses grid graphics
# install.packages("hexbin")
# install.packages("Hmisc")
install.packages("igraph")
install.packages(igraph)
install.packages("irr")
install.packages("ks")
# install.packages("kSamples")
install.packages("kSamples")
# install.packages("lattice")
install.packages("lattice")
install.packages(lattice)
install.packages("latticeExtra")
# install.packages("lme4")
install.packages("lme4")
install.packages(lme4)
#install.packages("lmerTest")
install.packages("lmodel2")
install.packages("lubridate")
# install.packages("MASS")
install.packages("MASS")
install.packages(MASS)
install.packages("Matrix") # sparse.model.matrix is referenced by a function in quantreg
install.packages("mgcv")
install.packages("mixtools")
install.packages(mvtnorm)
# install.packages("nlme")
install.packages("nlme")
install.packages(pdq)
install.packages("penalized")
# install.packages("plyr")
	install.packages(plyr)
install.packages("plyr")
install.packages(plyr)
install.packages("png")
install.packages("poweRlaw")
install.packages("prefmod")
install.packages("pwr")
install.packages("quantreg")
install.packages("Rcapture")
	install.packages(RColorBrewer)
# install.packages("rebmix")
install.packages("rebmix")
install.packages("relaimpo")
install.packages("reshape2")
install.packages("RJSONIO")
install.packages(RJSONIO)
install.packages(Rmisc)
install.packages("rms")
install.packages(rms)
# install.packages("robustbase")
# install.packages(robustbase)
install.packages("robustbase")
install.packages("ROCR")
install.packages("rpart")
install.packages(rpart)
install.packages("RSQLite")
# install.packages(RSVGTipsDevice)
# install.packages("sandwich")
install.packages("scatterplot3d")
install.packages("seriation")
install.packages("simex")
# install.packages("sjPlot")
install.packages("sm")
install.packages("sna")
install.packages("snatm")
install.packages("splines")
install.packages("stringr")
install.packages("survival")
install.packages(survival)
install.packages("tm")
install.packages(tm)
install.packages("tm.plugin.mail")
install.packages("treemap")
# install.packages("TSclust")
install.packages("TSclust")
install.packages("VennDiagram")
install.packages("VGAM")
install.packages("vioplot")
install.packages("visreg")
# install.packages("WRS")
install.packages("WRS")
install.packages("XML")
install.packages("zoo")
