grep -v -E "((RAS KERNEL FATAL (auxiliary processor|CHECK_INITIAL_GLOBAL_INTERRUPT_VALUES|core configuration register:|data address space|data address:|exception syndrome register:|floating point operation|general purpose registers:|guaranteed instruction cache block touch|guaranteed data cache block touch|icache prefetch depth|icache prefetch threshold|instruction address:|instruction address space|machine check status register:|imprecise machine check|machine check interrupt|machine check: i-fetch|machine check summary|problem state (0=sup,1=usr)|program interrupt:|special purpose registers:|store operation))|RAS APP FATAL ciod: Error loading .+: (invalid or missing program image, Exec format error|program image too big|invalid or missing program image, No such file or directory))"

RAS APP FATAL ciod: LOGIN chdir(/p/gb2/draeger/benchmark/dat32k_060205) failed: No such file or directory

NULL RAS BGLMASTER FAILURE mmcs_server exited normally with exit code 13

 wait state enable
input interrupt enable
floating point instr. enabled
 machine check enable
debug wait enable

disable store gathering
disable apu instruction broadcast
disable trace broadcast
disable speculative access

22:00004cf8 23:66666667

