all: imag0038 imag0039 imag0042 imag0046 scan0002 scan0003 scan0006 scan0008 scan0022 scan0028 scan0032 scan0036 scan0038 scan0043 scan0049 scan0053 scan0055 scan0058 scan0064 study1 study2 study3 study4 study5 study6 study7 study8 study9 study10 study11 study12 study13 study14 study15 study16 study17 study18 study19 study20 study21 study22 study 23 study24 study25 study26 study27 study28

imag0038: imag0038.c
	gcc -c imag0038.c

imag0039: imag0039.c
	gcc -c imag0039.c

imag0042: imag0042.c
	gcc -c imag0042.c

imag0046: imag0046.c
	gcc -c imag0046.c

scan0002: scan0002.c
	gcc -c scan0002.c

scan0003: scan0003.c
	gcc -c scan0003.c

scan0006: scan0006.c
	gcc -c scan0006.c

scan0008: scan0008.c
	gcc -c scan0008.c

scan0018: scan0018.cpp
	g++ -c scan0018.cpp

scan0022: scan0022.c
	gcc -c scan0022.c

scan0028: scan0028.c
	javac scan0028.java

scan0032: scan0032.cpp
	g++ -c scan0032.cpp

scan0036: scan0036.c
	gcc -c scan0036.c

scan0038: scan0038.c
	gcc -c scan0028.c

scan0043: scan0043.c
	gcc -c scan0043.c

scan0049: scan0049.c
	gcc -c scan0049.c

scan0053: scan0053.c
	gcc -c scan0053.c

scan0055: scan0055.c
	gcc -c scan0055.c

scan0059: scan0059.c
	gcc -c scan0059.c

scan0064: scan0064.py
	python scan0064.py

study1: study1.java
	javac study1.java

study2: study2.java
	javac study2.java

study3: study3.java
	javac study3.java

study4: study4.java
	javac study4.java

study5: study5.java
	javac study5.java

study6: study6.java
	javac study6.java

study7: study7.java
	javac study7.java

study8: study8.c
	gcc -c study8.c

study9: study9.c
	gcc -c study9.c

study10: study10.c
	gcc -c study10.c

study11: study11.java
	javac study11.java

study12: study12.java
	javac study12.java

study13: study13.java
	javac study13.java

study14: study14.java
	javac study14.java

study15: study15.java
	javac study15.java

study16: study16.java
	javac study16.java

study17: study17.java
	javac study17.java

study18: study18.java
	javac study18.java

study19: study19.java
	javac study19.java

study20: study20.c
	gcc -c study20.c

study21: study21.c
	gcc -c study21.c

study22: study22.java
	javac study22.java

study23: study23.java
	javac study23.java

study24: study24.java
	javac study24.java

study25: study25.java
	javac study25.java

study26: study26.java
	javac study26.java

study27: study27.java
	javac study27.java

study28: study28.java
	javac study28.java